# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0d26c1c305a660831c38aec7876271fca3a62260cdc458802920213c5c7a6d103d1fe063fc99b0a450046384bd67016702eddca2d12ef47578506b8f183e2b5

test:
  secret_key_base: b1f23121aa472ebfc3f85a7193e379060313e3ab4803f251eb327bf07ec60d4a2f32fa2131093929b9769624b33ef70c95034c54697cddb15ec0a0f10e224e09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
